version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"  # 👈 Replace "ports" with "expose"

  cache:
    image: redis:6
    ports:
      - "6379"  # 👈 Same here

  web:
    build: ./web
    ports:
      - "8080"  # 👈 No host port binding, enables scaling
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: mydb
      CACHE_HOST: cache
      CACHE_PORT: 6379
    depends_on:
      - database
      - cache
