version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"  # ✅ Expose only for internal network access

  cache:
    image: redis:6
    expose:
      - "6379"  # ✅ Expose only for internal network access

  web:
    build: ./web
    ports:
      - "8080:8080"  # ✅ This exposes to your EC2 host's port for browser access
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: mydb
      CACHE_HOST: cache
      CACHE_PORT: 6379
    depends_on:
      - database
      - cache
