version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb   # 🔹 Match with app.py
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  cache:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: mydb   # 🔹 Match with app.py
      CACHE_HOST: cache
      CACHE_PORT: 6379
    depends_on:
      - database
      - cache
